/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisisnumerico;

/**
 *
 * @author kevin Figueroa
 */
public class frmTartaglia extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmTartaglia() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Tartaglia-Cardano");
        ocultar();
    }

    public void ocultar() {
        txtImagi.setVisible(false);
        txtImagina.setVisible(false);
        txtmas.setVisible(false);
        txtmenos.setVisible(false);
        txti.setVisible(false);
        txti2.setVisible(false);
    }

    public void mostrar() {
        txtImagi.setVisible(true);
        txtImagina.setVisible(true);
        txtmas.setVisible(true);
        txtmenos.setVisible(true);
        txti.setVisible(true);
        txti2.setVisible(true);
    }

//    public static double[] discriminante(double a, double b, double c) {
//        double h, g, d;
//        h = (3 * b - Math.pow(a, 2)) / 9;
//        g = (9 * a * b - 27 * c - 2 * Math.pow(a, 3)) / 54;
//        d = Math.pow(g, 2) + Math.pow(h, 3);
//
//        double valores[] = {d, h, g};
//        return valores;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        srBoton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRaiz3 = new javax.swing.JTextField();
        txtRaiz1 = new javax.swing.JTextField();
        txtRaiz2 = new javax.swing.JTextField();
        txtImagina = new javax.swing.JTextField();
        txtImagi = new javax.swing.JTextField();
        txti = new javax.swing.JLabel();
        txti2 = new javax.swing.JLabel();
        txtmas = new javax.swing.JLabel();
        txtmenos = new javax.swing.JLabel();
        txtFuncci = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Raices Polinomicas");

        srBoton.setText("procesar Raices");
        srBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srBotonActionPerformed(evt);
            }
        });

        jLabel5.setText("x3 =");

        jLabel6.setText("x1 =");

        jLabel7.setText("x2 =");

        txtRaiz3.setText("                                               ");

        txtRaiz1.setText("                                               ");

        txtRaiz2.setText("                                               ");

        txtImagina.setText("                ");

        txtImagi.setText("               ");
        txtImagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImagiActionPerformed(evt);
            }
        });

        txti.setText("i");

        txti2.setText("i");

        txtmas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtmas.setText("+");

        txtmenos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtmenos.setText("-");

        jLabel8.setText("f(x)=");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFuncci))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtRaiz3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(srBoton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel6)
                                        .addGap(21, 21, 21)
                                        .addComponent(txtRaiz1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtRaiz2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtmas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtImagi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtImagina, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txti, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txti2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(srBoton)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtRaiz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel7))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtRaiz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtImagi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txti)
                                .addComponent(txtmas)))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRaiz3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtImagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txti2)
                                    .addComponent(txtmenos)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtFuncci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srBotonActionPerformed

        double a, b, c, cubo;
        String f=txtFuncci.getText();
        
        double[] coeficientes= Funcion.SacarCoeficientes(f);
        a=coeficientes[1];
        b=coeficientes[2];
        c=coeficientes[3];
       cubo=coeficientes[0];

        if (cubo != 1) {
            a = a / cubo;
            b = b / cubo;
            c = c / cubo;
            cubo = 1;
        }

        double resp[] = ProcesoTarFerrari.tartaglia(a, b, c);

        if (resp.length == 4) {
            txtImagi.setText(String.valueOf(resp[3]));
            txtImagina.setText(String.valueOf(resp[3]));
            mostrar();
        } else {
            ocultar();
        }
        txtRaiz1.setText(String.valueOf(resp[0]));
        txtRaiz2.setText(String.valueOf(resp[1]));
        txtRaiz3.setText(String.valueOf(resp[2]));
    }//GEN-LAST:event_srBotonActionPerformed

    private void txtImagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTartaglia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTartaglia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTartaglia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTartaglia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTartaglia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton srBoton;
    private javax.swing.JTextField txtFuncci;
    private javax.swing.JTextField txtImagi;
    private javax.swing.JTextField txtImagina;
    private javax.swing.JTextField txtRaiz1;
    private javax.swing.JTextField txtRaiz2;
    private javax.swing.JTextField txtRaiz3;
    private javax.swing.JLabel txti;
    private javax.swing.JLabel txti2;
    private javax.swing.JLabel txtmas;
    private javax.swing.JLabel txtmenos;
    // End of variables declaration//GEN-END:variables
}
